spring:
  application:
    name: twitter-to-kafka-service
  profiles:
    active: twitter_to_kafka
  config:
    import: 'configserver:'
  cloud:
    config:
      name: twitter-to-kafka-service,config-client
#      uri: http://localhost:8888
      username: spring_cloud_user
      password: '{cipher}34294ec3bbd0601094149062dc3cfacffddd9a8bb7d64d33d30b9bdd8f930765'

encrypt:
  key: ${ENCRYPT_KEY}

log:
  app-name: twitter-to-kafka-service

twitter-to-kafka-service:
  enable-mock-tweets: true
